pipeline {
  parameters {
    string(name: 'DOCKER_REGISTRY', description: 'Docker registry to store the image', defaultValue: 'nrdiaz92/educacionit')
  }

  agent any

  stages {
    stage('Docker login') {
        steps {
            sh 'docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}'
        }
    }

    stage('Docker build') {
        steps {
            sh 'docker build -t ${env.DOCKER_REGISTRY}:clase10-${commit}'
        }
    }

    stage('Docker push') {
        steps {
            sh 'docker push ${env.DOCKER_REGISTRY}:clase10-${commit}'
        }
    }
  }
}